### PR TITLE
Fix installing tests in sdist, and include doc sources as well

### PR DESCRIPTION
**Pull request by mgorny**
- fix the `include` entry for tests to name the correct directory
- include documentation sources as well, to permit building offline docs

### CODE REVIEW

**Comment by hegjon** [comment]
I noticed that the tests was not included in the 2.0.0 release, they are useful for Fedora Linux when we make RPM packages, this allows us to detect bugs earlier.

**Comment by thatch45** [comment]
Thanks! I added a few more features and I am working on a 2.1.0 release right now

**Comment by thatch45** [comment]
Ok, I just pushed 2.1.0, let me know if you see any issues. I guess I am a bit rusty! it has been a few years since I have been pushing software releases :)

**Comment by hegjon** [comment]
Thanks, the 2.1.0 release builds and runs the unit tests on Fedora Linux with Python 3.12.0b4 https://koji.fedoraproject.org/koji/taskinfo?taskID=104458896

**Comment by mgorny** [comment]
Thanks. The sdist looks good now. You seem to have forgotten to push the tag but that's not a blocker for us anymore (still nice to fix that though).

**Comment by thatch45** [comment]
Thanks, I just pushed the tag. I need to add a release checklist!

**Comment by hegjon** [comment]
> Thanks, I just pushed the tag. I need to add a release checklist!

I like the way the maintainer of SILE does his checklist. For inspiration see https://github.com/sile-typesetter/sile/issues/1830

**Pull request merged**
