### PR TITLE
add crypto_box_easy to main branch

### PR DESCRIPTION
**Pull request by jheling**

### CODE REVIEW

**Comment by thatch45** [comment]
Thanks @jheling !
Let me see why these tests are failing, I need to cut a fresh release as well after this gets merged

**Comment by thatch45** [comment]
I see where the issues are, I need to do some cleanup here

**Comment by thatch45** [comment]
and by cleanup, I mean cleanup in libnacl, not this PR, this PR looks good

**Comment by thatch45** [comment]
The issue was on travis, new build pushed to pypi, version 1.7. thanks again!

**Comment by jheling** [comment]
Thank you for this library. It was very helpfull for my free@home/homeassistant project. Now the only function that was missing for me is part of the official library.  Best, Johan

**Pull request merged**
