### PR TITLE
Add regressiontest for crypto_onetimeauth_verify

### PR DESCRIPTION
**Pull request by kpcyrd**
```
>>> crypto_onetimeauth_verify(crypto_onetimeauth('yolo', 'secret'), 'yolo', 'secret')
'yolo'
>>>
>>> crypto_onetimeauth_verify(crypto_onetimeauth('yolo', 'forged'), 'yolo', 'secret')
'yolo'
>>>
```

https://gist.github.com/kpcyrd/1ec95f93b1b13f6af35c

### CODE REVIEW

**Comment by thatch45** [comment]
Just FYI @kpcyrd these tests had some failures, I will link you to my fixes when I push them :)

**Comment by kpcyrd** [comment]
Thanks, keep me posted. Is there an ETA for a new release?

**Comment by thatch45** [comment]
I am trying to get it out today, just a few more test fixes :)

**Comment by thatch45** [comment]
d2e70bae9211a9bb0f68de591d355c864d064c2f
fc95e003cac98a814745ffc18f82d6c76588d553
Are the fixes I made to get tests running again :)

**Comment by thatch45** [comment]
https://pypi.python.org/pypi/libnacl/1.4.3

@kpcyrd can haz a release, thanks!

**Pull request merged**
