### PR TITLE
use setuptools again - pip requires it anyhow.

### PR DESCRIPTION
**Pull request by mindw**
It's very hard to use modern Python without setuptools.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
If you pip install libnacl using pip, the setuptools module will be loaded and because of that, setuptools is what's going to be used...

**Comment by mindw** [comment]
Setuptools is the recommended tool to use for packaging -
https://python-packaging-user-guide.readthedocs.org/en/latest/current .
It enables a few handy capabilities:
* enable documentation build via "python setup.py build_sphinx"
* enable wheel support.
* and other staff not directly relevant to pynacl.

There are no advantages that I know of to support plain distutils
exclusively.


-gabi

**Comment by s0undt3ch** [comment]
You missed my point, there's no exclusive in the setup.py... It can either use distutils, or, setuptools... It does not force one over the other. Your change, however, forces the use of setuptools...

**Comment by thatch45** [comment]
The main reason I avoid setuptools is because it causes problems when building packages for some distros.

**Comment by mindw** [comment]
Can you please give some examples to which distros have these known issues? How do they deal all the other Python packages which require setuptools?
Is is acceptable to make setuptools the default with distutils as fallback?

**Comment by thatch45** [comment]
The main problem with setuptools is found in how they create application scripts, this can cause issues where it add setuptools as a runtime dep to packages and therefore tends to break package updates. Since this is not an issue with libnacl because it is a library I will concede and allow setuptools. Even though I think it is overkill and not needed, distutils does a fine job on its own

**Pull request merged**
